### PR TITLE
Provide easy access to MC used to L1 track testing

### PR DESCRIPTION
**Pull request by tomalin**
This provides easy access for interactive CMSSW jobs developing the L1 tracking.

### CODE REVIEW

**Comment by tomalin** [comment]
Hi, 
Is this PR waiting for anything?
Thanks,
Ian

**Comment by smuzaffar** [comment]
@tomalin , this looks good. It only has new files, so can be merged and included in IBs.
You do need to cleanup https://github.com/cms-sw/cmssw/pull/29381 though to not have any ref of these files. Currently https://github.com/cms-sw/cmssw/pull/29381 still have these files in the history . So I would suggest to squash the history to get rid of any ref to these data files.

**Comment by tomalin** [comment]
https://github.com/cms-sw/cmssw/pull/29381 has been merged. It needs the txt files from this PR, but this PR has not yet been merged. Is it waiting for anything?

**Comment by smuzaffar** [comment]
@tomalin , if this was needed by cms-sw/cmssw#29381  then it should have been tested together. Any idea why tests and relvals are running fine in IB even without these files?

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
+externals

**Comment by rekovic** [comment]
+1

**Pull request merged**
