### PR TITLE
Added PU200 particle gun MC and updated displaced muon samples

### PR DESCRIPTION
**Pull request by tomalin**
Added PU200 particle gun samples & updated displaced muon particle gun samples (since old ones were buggy).

### CODE REVIEW

**Comment by tomalin** [comment]
Is there any reason this has not been merged?

**Comment by mrodozov** [comment]
please test
can we test this new files usage with anything in cmssw ?

**Comment by silviodonato** [comment]
+1
@tomalin do you need this only in `11_2_X`?

**Comment by mrodozov** [comment]
+externals

**Comment by tomalin** [comment]
@silviodonato This is not needed for the HLT TDR, so does not need to go into 11_1. There is no rush therefore, but it would be nice to get this PR merged sometime.

**Comment by silviodonato** [comment]
merge

**Comment by silviodonato** [comment]
@tomalin the PR  has been merged in master (https://github.com/cms-sw/cmsdist/pull/6150 )

**Pull request merged**
